package hr.flowable.pictionairre

object Data {

  val YellowTerms = listOf(
    "Guitar",
    "Bicycle",
    "Umbrella",
    "Watch",
    "Camera",
    "Sunglasses",
    "Book",
    "Laptop",
    "Backpack",
    "Coffee mug",
    "Wallet",
    "Alarm clock",
    "Tennis racket",
    "Remote control",
    "Soccer ball",
    "Baseball bat",
    "Skateboard",
    "Headphones",
    "Suitcase",
    "Fishing rod",
    "Blender",
    "Toaster",
    "Microwave",
    "Piano",
    "Brush",
    "Binoculars",
    "Hammer",
    "Scissors",
    "Chessboard",
    "Telescope",
    "Iron",
    "Calculator",
    "Stapler",
    "Perfume bottle",
    "Lantern",
    "Guitar pick",
    "Sewing machine",
    "Compass",
    "Fire extinguisher",
    "Rolling pin",
    "Hula hoop",
    "Screwdriver",
    "Megaphone",
    "Thermometer",
    "Water bottle",
    "Paintbrush",
    "Sunglasses",
    "Wrench",
    "Hand fan"
  )
}
