package hr.flowable.pictionairre

object Data {

  val YellowTerms = setOf(
    "Yacht",
    "Notepad",
    "Luggage",
    "Dartboard",
    "Grill",
    "Anchor",
    "Wetsuit",
    "Aquarium",
    "Sewing machine",
    "Tennis Racket",
    "Sunscreen",
    "Nightlight",
    "Toaster",
    "Spatula",
    "Chessboard",
    "Ice Skates",
    "Nail Clippers",
    "Umbrella Stand",
    "Magnifying Glass",
    "Paddleboard",
    "Stapler",
    "Backpack",
    "Easel",
    "Extension Cord",
    "Umbrella",
    "Kettle",
    "Yoga Mat",
    "Skateboard",
    "Music Stand",
    "Remote control",
    "Apple",
    "Zen Garden",
    "Can Opener",
    "Wallet",
    "Piano",
    "Laptop",
    "Kettlebell",
    "Paint Roller",
    "Tennis racket",
    "Quill Pen",
    "Tennis Ball",
    "Oil Paints",
    "Yo-yo",
    "Inflatable Pool",
    "Inflatable Boat",
    "Hammer",
    "Binoculars",
    "Ukulele",
    "Ornament",
    "Desk",
    "Rope",
    "Lamp",
    "Blender",
    "Treadmill",
    "Headphones",
    "Compass",
    "Earbuds",
    "Jigsaw Puzzle",
    "Wrench",
    "Bicycle Helmet",
    "Coffee mug",
    "Envelope",
    "Hula hoop",
    "Camera",
    "Brush",
    "Paints",
    "Quill",
    "X-ray Film",
    "Eraser",
    "Marbles",
    "Hula Hoop",
    "Flip-flops",
    "Oar",
    "Sunglasses",
    "Xylophone",
    "Flashlight",
    "Javelin",
    "Necklace",
    "Drumsticks",
    "Zipper Pull",
    "Violin Bow",
    "Calculator",
    "Zipline Kit",
    "Screwdriver",
    "Ice Cream Scoop",
    "Watch",
    "Water Bottle",
    "Lantern",
    "Ointment",
    "Flute",
    "Quokka Plush Toy",
    "Alarm clock",
    "Basket",
    "X-ray",
    "Ice Pack",
    "Rolling pin",
    "Orange",
    "Guitar",
    "Alarm Clock",
    "Kite",
    "Handcuffs",
    "Guitar pick",
    "Candle",
    "Roller Skates",
    "Picnic Basket",
    "Volleyball",
    "Iron",
    "Hammock",
    "Apron",
    "Fishing rod",
    "Water bottle",
    "Quilt",
    "Ladder",
    "Jump Rope",
    "Harmonica",
    "Beach Towel",
    "Paintbrush",
    "Fire extinguisher",
    "Hat",
    "Snorkel",
    "Soccer ball",
    "Suitcase",
    "Recorder",
    "Scissors",
    "Baseball bat",
    "Quilted Blanket",
    "Fork",
    "Pen",
    "Megaphone",
    "Dive Mask",
    "Map",
    "Globe",
    "Thermometer",
    "Fishing Rod",
    "Dumbbell",
    "Book",
    "Rollerblades",
    "Perfume bottle",
    "Violin",
    "Telescope",
    "Bicycle",
    "Keychain",
    "Airplane",
    "Notebook",
    "Zipper",
    "Inkwell",
    "Rug",
    "Radio",
    "Microwave",
    "Vase",
    "Hand fan",
    "Ocarina",
    "Chalkboard",
    "Dice",
    "Whistle",
  )

  val BlueTerms = setOf(
    "Dalai Lama",
    "Rio de Janeiro",
    "Cheetah",
    "Istanbul",
    "Michael Jordan",
    "Albert Einstein",
    "Malala Yousafzai",
    "Melbourne",
    "Seoul",
    "Marilyn Monroe",
    "Polar Bear",
    "San Francisco",
    "Armadillo",
    "Flamingo",
    "Wombat",
    "Kangaroo",
    "Rhinoceros",
    "Raccoon",
    "Shanghai",
    "Hedgehog",
    "Nairobi",
    "Elephant",
    "Whale",
    "John Lennon",
    "Panda",
    "Orangutan",
    "Cape Town",
    "Auckland",
    "Athens",
    "Winston Churchill",
    "Venice",
    "Vancouver",
    "Tom Hanks",
    "Beyoncé",
    "Prague",
    "Vienna",
    "Tiger",
    "David Beckham",
    "Elvis Presley",
    "Jennifer Aniston",
    "Michael Jackson",
    "Koala",
    "Moscow",
    "Snow Leopard",
    "Leonardo da Vinci",
    "Marie Curie",
    "Okapi",
    "Audrey Hepburn",
    "Mumbai",
    "Bob Marley",
    "Peacock",
    "Jellyfish",
    "Amelia Earhart",
    "Walrus",
    "Princess Diana",
    "Mantis Shrimp",
    "Steve Jobs",
    "Walt Disney",
    "Vincent van Gogh",
    "Muhammad Ali",
    "Stockholm",
    "Serena Williams",
    "Albert Camus",
    "Kyoto",
    "Charles Darwin",
    "Ostrich",
    "London",
    "Leonardo DiCaprio",
    "Sloth",
    "Isaac Newton",
    "Seahorse",
    "Nelson Mandela",
    "Frida Kahlo",
    "Platypus",
    "Giraffe",
    "Los Angeles",
    "Penguin",
    "Edinburgh",
    "Dubai",
    "Adele",
    "Barcelona",
    "Llama",
    "Sydney",
    "Kim Kardashian",
    "Alligator",
    "Amsterdam",
    "Bangkok",
    "Alpaca",
    "Parrot",
    "Puma",
    "Bison",
    "William Shakespeare",
    "Antelope",
    "Crocodile",
    "Pablo Picasso",
    "Berlin",
    "Bill Gates",
    "Manatee",
    "Havana",
    "Lion",
    "Cristiano Ronaldo",
    "Stephen Hawking",
    "Singapore",
    "Octopus",
    "Cairo",
    "Zurich",
    "Anne Frank",
    "Camel",
    "Oprah Winfrey",
    "Montreal",
    "Rome",
    "Tokyo",
    "Jerusalem",
    "Florence",
    "Meerkat",
    "Toronto",
    "Elon Musk",
    "Chimpanzee",
    "George Washington",
    "Reykjavik",
    "Angelina Jolie",
    "Marrakech",
    "Zebra",
    "Red Panda",
    "Barack Obama",
    "Buenos Aires",
    "Tapir",
    "Martin Luther King Jr.",
    "Beijing",
    "Honolulu",
    "Lemur",
    "Dolphin",
    "Jane Austen",
    "Gorilla",
    "Queen Elizabeth II",
    "Madonna",
    "Lima",
    "Mother Teresa",
    "Paris",
    "New York City",
    "Mahatma Gandhi",
    "Toucan",
    "Dublin",
  )

  val GreenTerms = setOf(
    "Balloon Pop Relay",
    "Tissue Box Dance",
    "Hopping Sack Race",
    "Balloon Volleyball",
    "Musical Beach Towels",
    "Ring Toss",
    "Drawing with Eyes Closed",
    "Who Am I?",
    "Spin the Bottle",
    "Skipping Challenge",
    "Duck Duck Goose",
    "Dance Floor Puzzle",
    "Stacking Cups",
    "Beatboxing",
    "Egg and Spoon Race",
    "Bubble Wrap Stomp",
    "Balancing Act",
    "Stilt Walking",
    "Dance-off",
    "Building a Card Tower",
    "Dance Tag",
    "Reverse Charades",
    "Guess the Movie Scene",
    "Stuffed Animal Dance-off",
    "Yoga Pose Challenge",
    "Balloon Back-and-Forth",
    "Water Balloon Relay",
    "Pencil Roll Race",
    "Cartwheel",
    "Karaoke Challenge",
    "Word Building Challenge",
    "Dress Up Relay",
    "Catching Bubbles",
    "Musical Chairs",
    "Red Light, Green Light",
    "Balancing on One Foot",
    "Cup Stacking",
    "Dance Circle",
    "Word Association",
    "Sticker Challenge",
    "Musical Drawing",
    "Duck, Duck, Gray Duck",
    "Stuffed Animal Relay",
    "Whisper Challenge",
    "Whistle Tunes",
    "Pencil Balance Challenge",
    "Headstand",
    "Spelling Bee",
    "Alphabet Hop",
    "Simon Shouts",
    "Charades",
    "Jump Rope Race",
    "Pantomime",
    "Mummy Wrap",
    "Trivia Quiz",
    "Drawing with Mouth",
    "Dance Statue",
    "Shoe Tying Relay",
    "Blindfolded Maze",
    "Human Ring Toss",
    "Guess the Emoji",
    "Jumping Jacks Relay",
    "Human Knot",
    "Lemon and Spoon Race",
    "Dance Follow the Leader",
    "Freeze Dance",
    "Drawing Race",
    "Human Pyramid",
    "Balloon Balance Relay",
    "Egg Drop Challenge",
    "Hopping Relay",
    "Pass the Parcel",
    "Bubble Blowing Contest",
    "Juggling",
    "Paper Bag Race",
    "Egg Toss",
    "Skipping Rope",
    "Group Storytelling",
    "Stencil Race",
    "Water Balloon Toss",
    "Marshmallow Tower",
    "Tug of War",
    "Balloon Dance",
    "Handstand",
    "Telephone Game",
    "Paper Airplane Contest",
    "Bouncing Ball Contest",
    "Balloon Animal Relay",
    "Musical Stomp",
    "Hoop Rolling",
    "Backward Race",
    "Musical Bumps",
    "Hula Hoop",
    "Shadow Puppets",
    "Bean Bag Toss",
    "Group Jumping Jacks",
    "Beach Ball Race",
    "Balloon Toss Relay",
    "Follow the Leader",
    "Partner Yoga",
    "Dizzy Bat Race",
    "Musical Statues",
    "Balloon Balancing Race",
    "Three-Legged Race",
    "Hot Potato",
    "Capture the Flag",
    "Whistling",
    "Sack Race",
    "Balloon Toss Dance",
    "Group Yoga",
    "Beach Ball Relay",
    "Egg Roll",
    "Doodle Challenge",
    "Skipping Rope Relay",
    "Balloon Animals",
    "Potato Sack Race",
    "Scavenger Hunt",
    "Balloon Stomp",
    "Popping Balloons",
    "Guess the Sound",
    "Red Light Green Light",
    "Stuffed Animal Relay Dance",
    "Hand Clapping Games",
    "Dance Mimicry",
    "Water Relay Race",
    "Plank Challenge",
    "Face Painting",
    "Group Dance Routine",
    "Partner Drawing",
    "Drawing Relay",
    "Name That Tune",
    "Pictionary Relay",
    "Spinning Around Race",
    "Stencil Drawing",
    "Straw Race",
    "Staring Contest",
    "Puzzle Building Race",
    "Guess the Riddle",
    "Rock Paper Scissors",
    "Limbo Dance",
    "Hopscotch",
    "Flag Relay Race",
    "Marshmallow and Toothpick Structures",
    "Copycat Game",
    "Dance Limbo",
    "Hopping Race",
    "Balloon Racket Relay",
    "Tongue Twisters",
    "Mime",
    "Chain Reaction",
    "Thumb Wrestling",
    "Animal Imitations",
    "Backward Dance Challenge",
    "Simon Says",
    "Dance Puzzle",
    "Rock, Paper, Scissors",
    "Duck Hunt",
    "Marshmallow Challenge",
    "Duck, Duck, Goose",
    "Stomp the Balloon",
  )

  val OrangeTerms = setOf(
    "Cooking",
    "Playing Xylophone",
    "Playing Oboe",
    "Doing Cha-Cha Dance",
    "Playing Tennis",
    "Surfing",
    "Playing Snooker",
    "Sunbathing",
    "Playing Chess",
    "Doing Crossword Puzzle",
    "Playing Ukulele",
    "Playing Tambourine",
    "Rock Climbing",
    "Hugging",
    "Shopping",
    "Doing Quickstep Dance",
    "Gardening",
    "Skydiving",
    "Doing Ballet",
    "Doing Jive Dance",
    "Doing Jumping Jacks",
    "Playing Glockenspiel",
    "Climbing",
    "Jumping Rope",
    "Kicking",
    "Playing Baglama",
    "Playing Flute",
    "Playing Marimba",
    "Doing Bollywood Dance",
    "Playing Bingo",
    "Playing Cowbell",
    "Playing Drums",
    "Singing",
    "Playing Hula Hoop",
    "Playing Maracas",
    "Playing Conga Drums",
    "Playing Baseball",
    "Playing Harmonica",
    "Doing Tai Chi",
    "Doing Bhangra Dance",
    "Doing Flamenco Dance",
    "Riding a Roller Coaster",
    "Riding a Horse",
    "Playing Triangle",
    "Doing Zumba",
    "Playing Trumpet",
    "Playing Cello",
    "Doing Capoeira",
    "Doing Waltz Dance",
    "Swimming",
    "Playing Golf",
    "Doing Pilates",
    "Playing Volleyball",
    "Playing Accordion",
    "Doing Lambada Dance",
    "Sleeping",
    "Texting",
    "Doing Breakdance",
    "Doing Macarena Dance",
    "Taking a Selfie",
    "Doing Push-Ups",
    "Doing Can-Can Dance",
    "Listening to Music",
    "Writing",
    "Bowling",
    "Taking Photos",
    "Watching TV",
    "Playing Violin",
    "Playing Soccer",
    "Ice Skating",
    "Driving",
    "Brushing Teeth",
    "Meditating",
    "Doing Foxtrot Dance",
    "Rollerblading",
    "Painting",
    "Playing Double Bass",
    "Doing Karate",
    "Playing Castanets",
    "Playing Recorder",
    "Playing Banjo",
    "Doing Line Dance",
    "Reading",
    "Dancing",
    "Doing Salsa Dance",
    "Doing Tap Dance",
    "Playing Didgeridoo",
    "Doing CrossFit",
    "Playing Ping Pong",
    "Doing Rumba Dance",
    "Washing Dishes",
    "Playing Basketball",
    "Playing Taiko Drum",
    "Flying",
    "Doing Tango Dance",
    "Eating",
    "Doing Samba Dance",
    "Jumping",
    "Doing Judo",
    "Doing Yoga",
    "Doing Swing Dance",
    "Doing Twist Dance",
    "Playing Saxophone",
    "Playing Badminton",
    "Playing Clarinet",
    "Doing a Handstand",
    "Knitting",
    "Playing Sitar",
    "Doing Ballet Dance",
    "Playing Slide Whistle",
    "Playing Piano",
    "Doing Parkour",
    "Doing Haka Dance",
    "Playing Tuba",
    "Playing Concertina",
    "Playing Mouth Organ",
    "Running",
    "Doing Polka Dance",
    "Doing Belly Dance",
    "Playing Bongo Drums",
    "Riding a Bike",
    "Fishing",
    "Playing Theremin",
    "Playing Djembe",
    "Doing Charleston Dance",
    "Playing Piccolo",
    "Crying",
    "Laughing",
    "Playing Bagpipes",
    "Doing Mambo Dance",
    "Playing Trombone",
    "Skiing",
    "Playing Kazoo",
    "Playing Kalimba",
    "Doing Hip Hop Dance",
    "Playing Guitar",
  )

  val RedTerms = setOf(
    "Umbrella",
    "Nightlight",
    "Pencil Roll Race",
    "Balancing Act",
    "Extension Cord",
    "Grill",
    "Ring Toss",
    "Musical Beach Towels",
    "Kangaroo",
    "Hedgehog",
    "Balloon Back-and-Forth",
    "Playing Tambourine",
    "Stapler",
    "Drawing with Eyes Closed",
    "Reverse Charades",
    "Playing Glockenspiel",
    "Rhinoceros",
    "Cheetah",
    "Easel",
    "Karaoke Challenge",
    "Playing Flute",
    "Doing Cha-Cha Dance",
    "Backpack",
    "Whale",
    "San Francisco",
    "Guess the Movie Scene",
    "Kettle",
    "Playing Ukulele",
    "Rio de Janeiro",
    "Raccoon",
    "Malala Yousafzai",
    "Stacking Cups",
    "Bubble Wrap Stomp",
    "Skipping Challenge",
    "Balloon Pop Relay",
    "Marilyn Monroe",
    "Luggage",
    "Balloon Volleyball",
    "Surfing",
    "Dartboard",
    "Tissue Box Dance",
    "Skydiving",
    "Shanghai",
    "Umbrella Stand",
    "Doing Crossword Puzzle",
    "Playing Xylophone",
    "Cooking",
    "Music Stand",
    "Sewing machine",
    "Yoga Mat",
    "Winston Churchill",
    "Yacht",
    "Dance Floor Puzzle",
    "Building a Card Tower",
    "Doing Jumping Jacks",
    "Wombat",
    "Ice Skates",
    "Nairobi",
    "Cape Town",
    "Orangutan",
    "Aquarium",
    "Playing Tennis",
    "Flamingo",
    "Michael Jordan",
    "Hugging",
    "Dance Tag",
    "Dance-off",
    "Egg and Spoon Race",
    "Skateboard",
    "Water Balloon Relay",
    "Athens",
    "Jumping Rope",
    "Doing Bollywood Dance",
    "Armadillo",
    "Climbing",
    "Albert Einstein",
    "Paddleboard",
    "Polar Bear",
    "Dalai Lama",
    "Wetsuit",
    "Kicking",
    "Panda",
    "Melbourne",
    "Istanbul",
    "Yoga Pose Challenge",
    "Doing Quickstep Dance",
    "Who Am I?",
    "Notepad",
    "Playing Baglama",
    "John Lennon",
    "Auckland",
    "Magnifying Glass",
    "Anchor",
    "Stilt Walking",
    "Toaster",
    "Elephant",
    "Duck Duck Goose",
    "Playing Snooker",
    "Chessboard",
    "Tennis Racket",
    "Playing Oboe",
    "Stuffed Animal Dance-off",
    "Playing Bingo",
    "Spin the Bottle",
    "Sunscreen",
    "Seoul",
    "Rock Climbing",
    "Beatboxing",
    "Cartwheel",
    "Nail Clippers",
    "Gardening",
    "Sunbathing",
    "Shopping",
    "Spatula",
    "Remote control",
    "Hopping Sack Race",
    "Doing Jive Dance",
    "Playing Chess",
    "Playing Marimba",
    "Doing Ballet",
  )
}
