package hr.flowable.pictionairre

object Data {

  val YellowTerms = setOf(
    "Yacht",
    "Notepad",
    "Luggage",
    "Dartboard",
    "Grill",
    "Anchor",
    "Wetsuit",
    "Aquarium",
    "Sewing machine",
    "Tennis Racket",
    "Sunscreen",
    "Nightlight",
    "Toaster",
    "Spatula",
    "Chessboard",
    "Ice Skates",
    "Nail Clippers",
    "Umbrella Stand",
    "Magnifying Glass",
    "Paddleboard",
    "Stapler",
    "Backpack",
    "Easel",
    "Extension Cord",
    "Umbrella",
    "Kettle",
    "Yoga Mat",
    "Skateboard",
    "Music Stand",
    "Remote control",
    "Apple",
    "Zen Garden",
    "Can Opener",
    "Wallet",
    "Piano",
    "Laptop",
    "Kettlebell",
    "Paint Roller",
    "Tennis racket",
    "Quill Pen",
    "Tennis Ball",
    "Oil Paints",
    "Yo-yo",
    "Inflatable Pool",
    "Inflatable Boat",
    "Hammer",
    "Binoculars",
    "Ukulele",
    "Ornament",
    "Desk",
    "Rope",
    "Lamp",
    "Blender",
    "Treadmill",
    "Headphones",
    "Compass",
    "Earbuds",
    "Jigsaw Puzzle",
    "Wrench",
    "Bicycle Helmet",
    "Coffee mug",
    "Envelope",
    "Hula hoop",
    "Camera",
    "Brush",
    "Paints",
    "Quill",
    "X-ray Film",
    "Eraser",
    "Marbles",
    "Hula Hoop",
    "Flip-flops",
    "Oar",
    "Sunglasses",
    "Xylophone",
    "Flashlight",
    "Javelin",
    "Necklace",
    "Drumsticks",
    "Zipper Pull",
    "Violin Bow",
    "Calculator",
    "Zipline Kit",
    "Screwdriver",
    "Ice Cream Scoop",
    "Watch",
    "Water Bottle",
    "Lantern",
    "Ointment",
    "Flute",
    "Quokka Plush Toy",
    "Alarm clock",
    "Basket",
    "X-ray",
    "Ice Pack",
    "Rolling pin",
    "Orange",
    "Guitar",
    "Alarm Clock",
    "Kite",
    "Handcuffs",
    "Guitar pick",
    "Candle",
    "Roller Skates",
    "Picnic Basket",
    "Volleyball",
    "Iron",
    "Hammock",
    "Apron",
    "Fishing rod",
    "Water bottle",
    "Quilt",
    "Ladder",
    "Jump Rope",
    "Harmonica",
    "Beach Towel",
    "Paintbrush",
    "Fire extinguisher",
    "Hat",
    "Snorkel",
    "Soccer ball",
    "Suitcase",
    "Recorder",
    "Scissors",
    "Baseball bat",
    "Quilted Blanket",
    "Fork",
    "Pen",
    "Megaphone",
    "Dive Mask",
    "Map",
    "Globe",
    "Thermometer",
    "Fishing Rod",
    "Dumbbell",
    "Book",
    "Rollerblades",
    "Perfume bottle",
    "Violin",
    "Telescope",
    "Bicycle",
    "Keychain",
    "Airplane",
    "Notebook",
    "Zipper",
    "Inkwell",
    "Rug",
    "Radio",
    "Microwave",
    "Vase",
    "Hand fan",
    "Ocarina",
    "Chalkboard",
    "Dice",
    "Whistle",
  )

  val BlueTerms = setOf(
    "Dalai Lama",
    "Rio de Janeiro",
    "Cheetah",
    "Istanbul",
    "Michael Jordan",
    "Albert Einstein",
    "Malala Yousafzai",
    "Melbourne",
    "Seoul",
    "Marilyn Monroe",
    "Polar Bear",
    "San Francisco",
    "Armadillo",
    "Flamingo",
    "Wombat",
    "Kangaroo",
    "Rhinoceros",
    "Raccoon",
    "Shanghai",
    "Hedgehog",
    "Nairobi",
    "Elephant",
    "Whale",
    "John Lennon",
    "Panda",
    "Orangutan",
    "Cape Town",
    "Auckland",
    "Athens",
    "Winston Churchill",
    "Venice",
    "Vancouver",
    "Tom Hanks",
    "Beyoncé",
    "Prague",
    "Vienna",
    "Tiger",
    "David Beckham",
    "Elvis Presley",
    "Jennifer Aniston",
    "Michael Jackson",
    "Koala",
    "Moscow",
    "Snow Leopard",
    "Leonardo da Vinci",
    "Marie Curie",
    "Okapi",
    "Audrey Hepburn",
    "Mumbai",
    "Bob Marley",
    "Peacock",
    "Jellyfish",
    "Amelia Earhart",
    "Walrus",
    "Princess Diana",
    "Mantis Shrimp",
    "Steve Jobs",
    "Walt Disney",
    "Vincent van Gogh",
    "Muhammad Ali",
    "Stockholm",
    "Serena Williams",
    "Albert Camus",
    "Kyoto",
    "Charles Darwin",
    "Ostrich",
    "London",
    "Leonardo DiCaprio",
    "Sloth",
    "Isaac Newton",
    "Seahorse",
    "Nelson Mandela",
    "Frida Kahlo",
    "Platypus",
    "Giraffe",
    "Los Angeles",
    "Penguin",
    "Edinburgh",
    "Dubai",
    "Adele",
    "Barcelona",
    "Llama",
    "Sydney",
    "Kim Kardashian",
    "Alligator",
    "Amsterdam",
    "Bangkok",
    "Alpaca",
    "Parrot",
    "Puma",
    "Bison",
    "William Shakespeare",
    "Antelope",
    "Crocodile",
    "Pablo Picasso",
    "Berlin",
    "Bill Gates",
    "Manatee",
    "Havana",
    "Lion",
    "Cristiano Ronaldo",
    "Stephen Hawking",
    "Singapore",
    "Octopus",
    "Cairo",
    "Zurich",
    "Anne Frank",
    "Camel",
    "Oprah Winfrey",
    "Montreal",
    "Rome",
    "Tokyo",
    "Jerusalem",
    "Florence",
    "Meerkat",
    "Toronto",
    "Elon Musk",
    "Chimpanzee",
    "George Washington",
    "Reykjavik",
    "Angelina Jolie",
    "Marrakech",
    "Zebra",
    "Red Panda",
    "Barack Obama",
    "Buenos Aires",
    "Tapir",
    "Martin Luther King Jr.",
    "Beijing",
    "Honolulu",
    "Lemur",
    "Dolphin",
    "Jane Austen",
    "Gorilla",
    "Queen Elizabeth II",
    "Madonna",
    "Lima",
    "Mother Teresa",
    "Paris",
    "New York City",
    "Mahatma Gandhi",
    "Toucan",
    "Dublin",
  )

  val GreenTerms = setOf(
    "Between Scylla and Charybdis",
    "Caught Between a Rock and a Hard Place",
    "Raining Cats and Dogs",
    "Hitting the Wall",
    "Hitting the Nail on the Head",
    "Bringing Home the Bacon",
    "Walking a Tightrope",
    "Tilting at Windmills",
    "Spinning Your Wheels",
    "Pulling Out All the Stops",
    "The Ball Is in Your Court",
    "Back to Square One",
    "Playing Hard to Get",
    "Don't Count Your Chickens Before They Hatch",
    "Poking the Hornet's Nest",
    "Bending Over Backwards",
    "In the Doghouse",
    "A Penny for Your Thoughts",
    "Setting the World on Fire",
    "Burning the Midnight Oil",
    "Raising Eyebrows",
    "On Thin Ice",
    "Skeletons in the Closet",
    "Beating a Dead Horse",
    "All Bark and No Bite",
    "Don't Judge a Book by Its Cover",
    "Rocking the Boat",
    "Beating the Bushes",
    "Living on Borrowed Time",
    "Penny Wise, Pound Foolish",
    "Kicking the Can Down the Road",
    "The Best of Both Worlds",
    "Falling Head over Heels",
    "A Dime a Dozen",
    "Don't Cry Over Spilled Milk",
    "Keeping Your Cards Close to Your Chest",
    "Cold Turkey",
    "Elephant in the Room",
    "The Devil Is in the Details",
    "All Greek to Me",
    "Up in Arms",
    "Weighing Your Options",
    "Going the Extra Mile",
    "Throwing a Curveball",
    "Leave No Stone Unturned",
    "Going Against the Grain",
    "Keeping Up with the Joneses",
    "Kicking the Tires",
    "Robbing Peter to Pay Paul",
    "On Cloud Nine",
    "Making a Silk Purse out of a Sow's Ear",
    "Letting the Cat out of the Bag",
    "Jumping on the Bandwagon",
    "The Whole Nine Yards",
    "Falling Flat on Your Face",
    "Making Hay while the Sun Shines",
    "Let Sleeping Dogs Lie",
    "A Leopard Can't Change Its Spots",
    "Throwing in the Towel",
    "Born with a Silver Spoon in Your Mouth",
    "Turning Over a New Leaf",
    "Crying Over Spilled Milk",
    "Raising the Roof",
    "Riding Shotgun",
    "Biting Off More Than You Can Chew",
    "Going Down the Rabbit Hole",
    "Shifting the Goalposts",
    "Walking on Eggshells",
    "Making a Mountain Out of a Molehill",
    "Hitting Below the Belt",
    "Stirring the Pot",
    "Close But No Cigar",
    "Don't Look a Gift Horse in the Mouth",
    "Out of the Woods",
    "Between the Devil and the Deep Blue Sea",
    "Nip in the Bud",
    "Having Your Cake and Eating It Too",
    "Playing Second Fiddle",
    "Taking the Bull by the Horns",
    "Chasing Rainbows",
    "Stealing Someone's Thunder",
    "The Early Bird Catches the Worm",
    "Cutting the Mustard",
    "Sweeping It under the Rug",
    "Every Cloud Has a Silver Lining",
    "Winning by a Landslide",
    "Jumping through Hoops",
    "A Stitch in Time Saves Nine",
    "Back to the Drawing Board",
    "Biting the Bullet",
    "Casting Pearls before Swine",
    "Cutting the Cheese",
    "Running around Like a Chicken with Its Head Cut Off",
    "Tugging at Heartstrings",
    "Making Ends Meet",
    "Over the Moon",
    "Castles in the Air",
    "Barking Up the Wrong Tree",
    "Flying by the Seat of Your Pants",
    "Cutting Corners",
    "Sleeping with the Fishes",
    "In the Dog House",
    "Splitting Hairs",
    "Against All Odds",
    "Out on a Limb",
    "Barking Up the Wrong Telephone Pole",
    "A Fish Out of Water",
    "Robbing the Cradle",
    "Running on Empty",
    "Weighing the Pros and Cons",
    "Out of the Frying Pan and into the Fire",
    "Ruffling Feathers",
    "Walking the Tightrope",
    "Cock and Bull Story",
    "Hitting the Ground Running",
    "Painting the Town Red",
    "Putting All Your Eggs in One Basket",
    "Throwing Caution to the Wind",
    "Back to Square Zero",
    "Between a Rock and a Hard Place",
    "A Drop in the Bucket",
    "On the Back Burner",
    "Shaking a Leg",
    "A Fool and His Money Are Soon Parted",
    "Up in the Air",
    "A Wolf in Sheep's Clothing",
    "Fish Out of Water",
    "Crying Wolf",
    "Putting the Cart Before the Horse",
    "Winning by a Nose",
    "Caught Red-Handed",
    "Burying Your Head in the Sand",
    "Shooting the Breeze",
    "In the Same Boat",
    "Bite the Bullet",
    "Painting Yourself into a Corner",
    "Jumping Ship",
    "A Bird in the Hand Is Worth Two in the Bush",
    "Devil's Advocate",
    "Bounce off the Walls",
    "Beating Around the Bush",
    "Kicking the Bucket",
    "Rule of Thumb",
    "Let the Cat out of the Bag",
    "Throwing in the Sponge",
    "Flogging a Dead Horse",
    "Living High on the Hog",
    "Burning the Candle at Both Ends",
    "Playing It by Ear",
  )

  val OrangeTerms = setOf(
    "Cooking",
    "Playing Xylophone",
    "Playing Oboe",
    "Doing Cha-Cha Dance",
    "Playing Tennis",
    "Surfing",
    "Playing Snooker",
    "Sunbathing",
    "Playing Chess",
    "Doing Crossword Puzzle",
    "Playing Ukulele",
    "Playing Tambourine",
    "Rock Climbing",
    "Hugging",
    "Shopping",
    "Doing Quickstep Dance",
    "Gardening",
    "Skydiving",
    "Doing Ballet",
    "Doing Jive Dance",
    "Doing Jumping Jacks",
    "Playing Glockenspiel",
    "Climbing",
    "Jumping Rope",
    "Kicking",
    "Playing Baglama",
    "Playing Flute",
    "Playing Marimba",
    "Doing Bollywood Dance",
    "Playing Bingo",
    "Playing Cowbell",
    "Playing Drums",
    "Singing",
    "Playing Hula Hoop",
    "Playing Maracas",
    "Playing Conga Drums",
    "Playing Baseball",
    "Playing Harmonica",
    "Doing Tai Chi",
    "Doing Bhangra Dance",
    "Doing Flamenco Dance",
    "Riding a Roller Coaster",
    "Riding a Horse",
    "Playing Triangle",
    "Doing Zumba",
    "Playing Trumpet",
    "Playing Cello",
    "Doing Capoeira",
    "Doing Waltz Dance",
    "Swimming",
    "Playing Golf",
    "Doing Pilates",
    "Playing Volleyball",
    "Playing Accordion",
    "Doing Lambada Dance",
    "Sleeping",
    "Texting",
    "Doing Breakdance",
    "Doing Macarena Dance",
    "Taking a Selfie",
    "Doing Push-Ups",
    "Doing Can-Can Dance",
    "Listening to Music",
    "Writing",
    "Bowling",
    "Taking Photos",
    "Watching TV",
    "Playing Violin",
    "Playing Soccer",
    "Ice Skating",
    "Driving",
    "Brushing Teeth",
    "Meditating",
    "Doing Foxtrot Dance",
    "Rollerblading",
    "Painting",
    "Playing Double Bass",
    "Doing Karate",
    "Playing Castanets",
    "Playing Recorder",
    "Playing Banjo",
    "Doing Line Dance",
    "Reading",
    "Dancing",
    "Doing Salsa Dance",
    "Doing Tap Dance",
    "Playing Didgeridoo",
    "Doing CrossFit",
    "Playing Ping Pong",
    "Doing Rumba Dance",
    "Washing Dishes",
    "Playing Basketball",
    "Playing Taiko Drum",
    "Flying",
    "Doing Tango Dance",
    "Eating",
    "Doing Samba Dance",
    "Jumping",
    "Doing Judo",
    "Doing Yoga",
    "Doing Swing Dance",
    "Doing Twist Dance",
    "Playing Saxophone",
    "Playing Badminton",
    "Playing Clarinet",
    "Doing a Handstand",
    "Knitting",
    "Playing Sitar",
    "Doing Ballet Dance",
    "Playing Slide Whistle",
    "Playing Piano",
    "Doing Parkour",
    "Doing Haka Dance",
    "Playing Tuba",
    "Playing Concertina",
    "Playing Mouth Organ",
    "Running",
    "Doing Polka Dance",
    "Doing Belly Dance",
    "Playing Bongo Drums",
    "Riding a Bike",
    "Fishing",
    "Playing Theremin",
    "Playing Djembe",
    "Doing Charleston Dance",
    "Playing Piccolo",
    "Crying",
    "Laughing",
    "Playing Bagpipes",
    "Doing Mambo Dance",
    "Playing Trombone",
    "Skiing",
    "Playing Kazoo",
    "Playing Kalimba",
    "Doing Hip Hop Dance",
    "Playing Guitar",
  )

  val RedTerms = setOf(
    "Pulling Out All the Stops",
    "Ice Skates",
    "Anchor",
    "Skeletons in the Closet",
    "Playing Tambourine",
    "Dartboard",
    "Living on Borrowed Time",
    "Dalai Lama",
    "Luggage",
    "Don't Judge a Book by Its Cover",
    "Seoul",
    "Cape Town",
    "Playing Hard to Get",
    "Playing Snooker",
    "Doing Crossword Puzzle",
    "Shanghai",
    "Poking the Hornet's Nest",
    "Whale",
    "Wombat",
    "Rhinoceros",
    "Caught Between a Rock and a Hard Place",
    "Cooking",
    "Playing Xylophone",
    "Melbourne",
    "Notepad",
    "On Thin Ice",
    "Bringing Home the Bacon",
    "Raining Cats and Dogs",
    "Back to Square One",
    "Remote control",
    "All Bark and No Bite",
    "Rocking the Boat",
    "Hedgehog",
    "Setting the World on Fire",
    "Between Scylla and Charybdis",
    "Polar Bear",
    "Music Stand",
    "Rock Climbing",
    "Playing Baglama",
    "Jumping Rope",
    "Tennis Racket",
    "Flamingo",
    "Malala Yousafzai",
    "Yoga Mat",
    "Skydiving",
    "Yacht",
    "Easel",
    "Gardening",
    "Raising Eyebrows",
    "Panda",
    "Istanbul",
    "Don't Count Your Chickens Before They Hatch",
    "A Penny for Your Thoughts",
    "Playing Flute",
    "Chessboard",
    "Doing Jumping Jacks",
    "Backpack",
    "Playing Chess",
    "Paddleboard",
    "Magnifying Glass",
    "Armadillo",
    "Playing Marimba",
    "Walking a Tightrope",
    "Playing Bingo",
    "Nail Clippers",
    "Tilting at Windmills",
    "Kettle",
    "Spinning Your Wheels",
    "Wetsuit",
    "Playing Oboe",
    "Orangutan",
    "Sewing machine",
    "Climbing",
    "Playing Glockenspiel",
    "Winston Churchill",
    "In the Doghouse",
    "Nairobi",
    "Rio de Janeiro",
    "San Francisco",
    "Playing Ukulele",
    "The Ball Is in Your Court",
    "Doing Quickstep Dance",
    "Beating a Dead Horse",
    "Albert Einstein",
    "Sunscreen",
    "Auckland",
    "Aquarium",
    "Athens",
    "Michael Jordan",
    "Doing Ballet",
    "John Lennon",
    "Doing Jive Dance",
    "Marilyn Monroe",
    "Grill",
    "Surfing",
    "Doing Cha-Cha Dance",
    "Nightlight",
    "Raccoon",
    "Doing Bollywood Dance",
    "Burning the Midnight Oil",
    "Beating the Bushes",
    "Bending Over Backwards",
    "Hugging",
    "Kicking",
    "Shopping",
    "Elephant",
    "Cheetah",
    "Stapler",
    "Sunbathing",
    "Umbrella Stand",
    "Skateboard",
    "Hitting the Wall",
    "Hitting the Nail on the Head",
    "Umbrella",
    "Spatula",
    "Toaster",
    "Playing Tennis",
    "Penny Wise, Pound Foolish",
    "Extension Cord",
    "Kangaroo",
  )
}
